import { z } from "zod";

export const itemSchema = z.object({
  id: z.string().default(""),
  item: z.number().min(1, "Item ID is required"),
  maxcount: z.number().default(0),
  incrtime: z.number().default(0),
  extendedcost: z.number().default(0),
  slot: z.number().default(-1),
});

export const vendorFormSchema = z.object({
  entry: z.number().min(1, "Entry ID is required").default(900001),
  name: z.string().min(1, "Name is required").default("New Vendor"),
  subname: z.string().default("Reagent Vendor"),
  modelid1: z.number().min(1).default(17591),
  minlevel: z.number().min(1).max(255).default(80),
  maxlevel: z.number().min(1).max(255).default(80),
  exp: z.number().default(2),
  faction: z.number().default(35),
  npcflag: z.number().default(128),
  speed_walk: z.number().default(1.0),
  speed_run: z.number().default(1.14286),
  unit_class: z.number().default(1),
  rank: z.number().default(0),
  type: z.number().default(7),
  items: z.array(itemSchema).default([]),
});

export type VendorFormValues = z.infer<typeof vendorFormSchema>;

export const duplicateFormSchema = z.object({
  source_entry: z.number().min(1, "Source Entry ID is required").default(1),
  new_entry: z.number().min(1, "New Entry ID is required").default(900002),
  new_name: z.string().default(""),
  new_subname: z.string().default(""),
  npc_type: z.string().default("vendor"),
});

export type DuplicateFormValues = z.infer<typeof duplicateFormSchema>;

// ── NPC Creator ─────────────────────────────────────────────────────────────

export const npcFormSchema = z.object({
  // creature_template
  entry: z.number().min(1, "Entry ID is required").default(601017),
  name: z.string().min(1, "Name is required").default("New NPC"),
  subname: z.string().default(""),
  iconname: z.string().default("Speak"),
  scriptname: z.string().default(""),
  gossip_menu_id: z.number().default(0),
  minlevel: z.number().min(1).max(255).default(80),
  maxlevel: z.number().min(1).max(255).default(80),
  exp: z.number().default(2),
  faction: z.number().default(35),
  npcflag: z.number().default(1),
  speed_walk: z.number().default(1.0),
  speed_run: z.number().default(1.14286),
  unit_class: z.number().default(1),
  rank: z.number().default(0),
  type: z.number().default(7),
  flags_extra: z.number().default(2),
  // creature_template_model
  display_id: z.number().default(14612),
  display_scale: z.number().default(1),
  model_verified_build: z.number().default(12340),
  // creature_equip_template
  equip_item1: z.number().default(0),
  equip_item2: z.number().default(0),
  equip_item3: z.number().default(0),
  equip_verified_build: z.number().default(18019),
  // creature_template_movement
  mov_ground: z.number().default(1),
  mov_swim: z.number().default(1),
  mov_flight: z.number().default(0),
  mov_rooted: z.number().default(0),
  mov_chase: z.number().default(0),
  mov_random: z.number().default(0),
});

export type NpcFormValues = z.infer<typeof npcFormSchema>;

// ── Helpers ──────────────────────────────────────────────────────────────────

function esc(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

// ── SQL generators ───────────────────────────────────────────────────────────

export function generateCreateSql(data: VendorFormValues): string {
  const {
    entry, name, subname, modelid1,
    minlevel, maxlevel, exp, faction, npcflag,
    speed_walk, speed_run,
    unit_class, rank, type,
    items,
  } = data;

  let sql = `-- ============================================\n`;
  sql += `-- Vendor: ${name} | Entry: ${entry}\n`;
  sql += `-- Generated by AzerothCore Vendor Creator\n`;
  sql += `-- Run this in your WORLD database\n`;
  sql += `-- ============================================\n\n`;
  sql += `USE \`acore_world\`;\n\n`;

  sql += `-- Step 1: creature_template\n`;
  sql += `DELETE FROM \`creature_template\` WHERE \`entry\` = ${entry};\n`;
  sql += `INSERT INTO \`creature_template\` (\n`;
  sql += `  \`entry\`, \`difficulty_entry_1\`, \`difficulty_entry_2\`, \`difficulty_entry_3\`,\n`;
  sql += `  \`KillCredit1\`, \`KillCredit2\`,\n`;
  sql += `  \`name\`, \`subname\`, \`IconName\`, \`gossip_menu_id\`,\n`;
  sql += `  \`minlevel\`, \`maxlevel\`, \`exp\`,\n`;
  sql += `  \`faction\`, \`npcflag\`,\n`;
  sql += `  \`speed_walk\`, \`speed_run\`, \`speed_swim\`, \`speed_flight\`, \`detection_range\`,\n`;
  sql += `  \`rank\`, \`dmgschool\`, \`DamageModifier\`,\n`;
  sql += `  \`BaseAttackTime\`, \`RangeAttackTime\`, \`BaseVariance\`, \`RangeVariance\`,\n`;
  sql += `  \`unit_class\`, \`unit_flags\`, \`unit_flags2\`, \`dynamicflags\`,\n`;
  sql += `  \`family\`, \`type\`, \`type_flags\`,\n`;
  sql += `  \`lootid\`, \`pickpocketloot\`, \`skinloot\`,\n`;
  sql += `  \`PetSpellDataId\`, \`VehicleId\`,\n`;
  sql += `  \`mingold\`, \`maxgold\`,\n`;
  sql += `  \`AIName\`, \`MovementType\`, \`HoverHeight\`,\n`;
  sql += `  \`HealthModifier\`, \`ManaModifier\`, \`ArmorModifier\`, \`ExperienceModifier\`,\n`;
  sql += `  \`RacialLeader\`, \`movementId\`, \`RegenHealth\`,\n`;
  sql += `  \`flags_extra\`, \`ScriptName\`, \`VerifiedBuild\`\n`;
  sql += `) VALUES (\n`;
  sql += `  ${entry}, 0, 0, 0,\n`;
  sql += `  0, 0,\n`;
  sql += `  '${esc(name)}', '${esc(subname)}', '', 0,\n`;
  sql += `  ${minlevel}, ${maxlevel}, ${exp ?? 2},\n`;
  sql += `  ${faction}, ${npcflag},\n`;
  sql += `  ${speed_walk.toFixed(5)}, ${speed_run.toFixed(5)}, 1.00000, 1.00000, 20.0,\n`;
  sql += `  ${rank}, 0, 1.0,\n`;
  sql += `  2000, 2000, 1.0, 1.0,\n`;
  sql += `  ${unit_class}, 0, 0, 0,\n`;
  sql += `  0, ${type}, 0,\n`;
  sql += `  0, 0, 0,\n`;
  sql += `  0, 0,\n`;
  sql += `  0, 0,\n`;
  sql += `  '', 0, 1.0,\n`;
  sql += `  1.0, 1.0, 1.0, 1.0,\n`;
  sql += `  0, 0, 1,\n`;
  sql += `  0, '', 0\n`;
  sql += `);\n\n`;

  sql += `-- Step 2: creature_template_model (NPC appearance)\n`;
  sql += `DELETE FROM \`creature_template_model\` WHERE \`CreatureID\` = ${entry};\n`;
  sql += `INSERT INTO \`creature_template_model\` (\`CreatureID\`, \`Idx\`, \`CreatureDisplayID\`, \`DisplayScale\`, \`Probability\`, \`VerifiedBuild\`) VALUES\n`;
  sql += `(${entry}, 0, ${modelid1}, 1, 1, 0);\n\n`;

  sql += `-- Step 3: npc_vendor (items sold)\n`;
  sql += `DELETE FROM \`npc_vendor\` WHERE \`entry\` = ${entry};\n`;
  if (items.length > 0) {
    sql += `INSERT INTO \`npc_vendor\` (\`entry\`, \`slot\`, \`item\`, \`maxcount\`, \`incrtime\`, \`ExtendedCost\`) VALUES\n`;
    const rows = items.map((item, index) => {
      const isLast = index === items.length - 1;
      return `(${entry}, ${item.slot}, ${item.item}, ${item.maxcount}, ${item.incrtime}, ${item.extendedcost})${isLast ? ";" : ","}`;
    });
    sql += rows.join("\n") + "\n";
  } else {
    sql += `-- No items added to vendor inventory.\n`;
  }

  return sql;
}

export function generateDuplicateSql(data: DuplicateFormValues): string {
  const { source_entry, new_entry, new_name, new_subname, npc_type } = data;

  const npcFlagMap: Record<string, number> = {
    vendor: 128,
    gossip: 1,
    trainer: 16,
    questgiver: 2,
    flightmaster: 32,
    vendor_gossip: 129,
    trainer_gossip: 17,
    questgiver_gossip: 3,
  };

  const npcflag = npcFlagMap[npc_type] ?? 128;

  let sql = `-- ============================================\n`;
  sql += `-- Duplicate Vendor: ${source_entry} -> ${new_entry}\n`;
  sql += `-- Generated by AzerothCore Vendor Creator\n`;
  sql += `-- Run this in your WORLD database\n`;
  sql += `-- ============================================\n\n`;
  sql += `USE \`acore_world\`;\n\n`;

  sql += `-- Step 1: Copy creature_template\n`;
  sql += `DELETE FROM \`creature_template\` WHERE \`entry\` = ${new_entry};\n`;

  const nameField = new_name ? `'${esc(new_name)}'` : `\`name\``;
  const subnameField = new_subname ? `'${esc(new_subname)}'` : `\`subname\``;

  sql += `INSERT INTO \`creature_template\` (\n`;
  sql += `  \`entry\`, \`difficulty_entry_1\`, \`difficulty_entry_2\`, \`difficulty_entry_3\`,\n`;
  sql += `  \`KillCredit1\`, \`KillCredit2\`,\n`;
  sql += `  \`name\`, \`subname\`, \`IconName\`, \`gossip_menu_id\`,\n`;
  sql += `  \`minlevel\`, \`maxlevel\`, \`exp\`,\n`;
  sql += `  \`faction\`, \`npcflag\`,\n`;
  sql += `  \`speed_walk\`, \`speed_run\`, \`speed_swim\`, \`speed_flight\`, \`detection_range\`,\n`;
  sql += `  \`rank\`, \`dmgschool\`, \`DamageModifier\`,\n`;
  sql += `  \`BaseAttackTime\`, \`RangeAttackTime\`, \`BaseVariance\`, \`RangeVariance\`,\n`;
  sql += `  \`unit_class\`, \`unit_flags\`, \`unit_flags2\`, \`dynamicflags\`,\n`;
  sql += `  \`family\`, \`type\`, \`type_flags\`,\n`;
  sql += `  \`lootid\`, \`pickpocketloot\`, \`skinloot\`,\n`;
  sql += `  \`PetSpellDataId\`, \`VehicleId\`,\n`;
  sql += `  \`mingold\`, \`maxgold\`,\n`;
  sql += `  \`AIName\`, \`MovementType\`, \`HoverHeight\`,\n`;
  sql += `  \`HealthModifier\`, \`ManaModifier\`, \`ArmorModifier\`, \`ExperienceModifier\`,\n`;
  sql += `  \`RacialLeader\`, \`movementId\`, \`RegenHealth\`,\n`;
  sql += `  \`flags_extra\`, \`ScriptName\`, \`VerifiedBuild\`\n`;
  sql += `)\n`;
  sql += `  SELECT ${new_entry}, \`difficulty_entry_1\`, \`difficulty_entry_2\`, \`difficulty_entry_3\`,\n`;
  sql += `    \`KillCredit1\`, \`KillCredit2\`, ${nameField}, ${subnameField}, \`IconName\`, \`gossip_menu_id\`,\n`;
  sql += `    \`minlevel\`, \`maxlevel\`, \`exp\`, \`faction\`, ${npcflag},\n`;
  sql += `    \`speed_walk\`, \`speed_run\`, \`speed_swim\`, \`speed_flight\`, \`detection_range\`,\n`;
  sql += `    \`rank\`, \`dmgschool\`, \`DamageModifier\`, \`BaseAttackTime\`, \`RangeAttackTime\`,\n`;
  sql += `    \`BaseVariance\`, \`RangeVariance\`, \`unit_class\`, \`unit_flags\`, \`unit_flags2\`,\n`;
  sql += `    \`dynamicflags\`, \`family\`, \`type\`, \`type_flags\`, \`lootid\`, \`pickpocketloot\`,\n`;
  sql += `    \`skinloot\`, \`PetSpellDataId\`, \`VehicleId\`, \`mingold\`, \`maxgold\`,\n`;
  sql += `    \`AIName\`, \`MovementType\`, \`HoverHeight\`, \`HealthModifier\`, \`ManaModifier\`,\n`;
  sql += `    \`ArmorModifier\`, \`ExperienceModifier\`, \`RacialLeader\`, \`movementId\`,\n`;
  sql += `    \`RegenHealth\`, \`flags_extra\`, \`ScriptName\`, 0\n`;
  sql += `  FROM \`creature_template\` WHERE \`entry\` = ${source_entry};\n\n`;

  sql += `-- Step 2: Copy creature_template_model (appearance)\n`;
  sql += `DELETE FROM \`creature_template_model\` WHERE \`CreatureID\` = ${new_entry};\n`;
  sql += `INSERT INTO \`creature_template_model\` (\`CreatureID\`, \`Idx\`, \`CreatureDisplayID\`, \`DisplayScale\`, \`Probability\`, \`VerifiedBuild\`)\n`;
  sql += `  SELECT ${new_entry}, \`Idx\`, \`CreatureDisplayID\`, \`DisplayScale\`, \`Probability\`, 0\n`;
  sql += `  FROM \`creature_template_model\` WHERE \`CreatureID\` = ${source_entry};\n\n`;

  sql += `-- Step 3: Copy npc_vendor (inventory)\n`;
  sql += `DELETE FROM \`npc_vendor\` WHERE \`entry\` = ${new_entry};\n`;
  sql += `INSERT INTO \`npc_vendor\` (\`entry\`, \`slot\`, \`item\`, \`maxcount\`, \`incrtime\`, \`ExtendedCost\`)\n`;
  sql += `  SELECT ${new_entry}, \`slot\`, \`item\`, \`maxcount\`, \`incrtime\`, \`ExtendedCost\`\n`;
  sql += `  FROM \`npc_vendor\` WHERE \`entry\` = ${source_entry};\n`;

  return sql;
}

export function generateNpcSql(data: NpcFormValues): string {
  const {
    entry, name, subname, iconname, scriptname, gossip_menu_id,
    minlevel, maxlevel, exp, faction, npcflag,
    speed_walk, speed_run, unit_class, rank, type, flags_extra,
    display_id, display_scale, model_verified_build,
    equip_item1, equip_item2, equip_item3, equip_verified_build,
    mov_ground, mov_swim, mov_flight, mov_rooted, mov_chase, mov_random,
  } = data;

  let sql = `-- ============================================\n`;
  sql += `-- NPC: ${name} | Entry: ${entry}\n`;
  sql += `-- Generated by AzerothCore Vendor Creator\n`;
  sql += `-- Run this in your WORLD database\n`;
  sql += `-- ============================================\n\n`;
  sql += `USE \`acore_world\`;\n\n`;

  // --- creature_template ---
  sql += `DELETE FROM \`creature_template\` WHERE (\`entry\` = ${entry});\n`;
  sql += `INSERT INTO \`creature_template\` (\`entry\`, \`difficulty_entry_1\`, \`difficulty_entry_2\`, \`difficulty_entry_3\`, \`KillCredit1\`, \`KillCredit2\`, \`name\`, \`subname\`, \`IconName\`, \`gossip_menu_id\`, \`minlevel\`, \`maxlevel\`, \`exp\`, \`faction\`, \`npcflag\`, \`speed_walk\`, \`speed_run\`, \`speed_swim\`, \`speed_flight\`, \`detection_range\`, \`rank\`, \`dmgschool\`, \`DamageModifier\`, \`BaseAttackTime\`, \`RangeAttackTime\`, \`BaseVariance\`, \`RangeVariance\`, \`unit_class\`, \`unit_flags\`, \`unit_flags2\`, \`dynamicflags\`, \`family\`, \`type\`, \`type_flags\`, \`lootid\`, \`pickpocketloot\`, \`skinloot\`, \`PetSpellDataId\`, \`VehicleId\`, \`mingold\`, \`maxgold\`, \`AIName\`, \`MovementType\`, \`HoverHeight\`, \`HealthModifier\`, \`ManaModifier\`, \`ArmorModifier\`, \`ExperienceModifier\`, \`RacialLeader\`, \`movementId\`, \`RegenHealth\`, \`flags_extra\`, \`ScriptName\`, \`VerifiedBuild\`) VALUES(`;
  const resolvedIcon = iconname === "__none__" ? "" : iconname;
  sql += `${entry}, 0, 0, 0, 0, 0, '${esc(name)}', '${esc(subname)}', '${esc(resolvedIcon)}', ${gossip_menu_id}, ${minlevel}, ${maxlevel}, ${exp ?? 2}, ${faction}, ${npcflag}, ${speed_walk}, ${speed_run.toFixed(5)}, 1, 1, 1, ${rank}, 0, 1, 0, 0, 0, 0, ${unit_class}, 0, 0, 0, 0, ${type}, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 1, 1, 1, 1, 1, 0, 0, 1, ${flags_extra}, '${esc(scriptname)}', 0);\n\n`;

  // --- creature_template_model ---
  sql += `DELETE FROM \`creature_template_model\` WHERE (\`CreatureID\` = ${entry});\n`;
  sql += `INSERT INTO \`creature_template_model\` (\`CreatureID\`, \`Idx\`, \`CreatureDisplayID\`, \`DisplayScale\`, \`Probability\`, \`VerifiedBuild\`) VALUES\n`;
  sql += `(${entry}, 1, ${display_id}, ${display_scale}, 1, ${model_verified_build});\n\n`;

  // --- creature_equip_template ---
  sql += `DELETE FROM \`creature_equip_template\` WHERE (\`CreatureID\` = ${entry});\n`;
  sql += `INSERT INTO \`creature_equip_template\` (\`CreatureID\`, \`ID\`, \`ItemID1\`, \`ItemID2\`, \`ItemID3\`, \`VerifiedBuild\`) VALUES\n`;
  sql += `(${entry}, 1, ${equip_item1}, ${equip_item2}, ${equip_item3}, ${equip_verified_build});\n\n`;

  // --- creature_template_movement ---
  sql += `DELETE FROM \`creature_template_movement\` WHERE (\`CreatureId\` = ${entry});\n`;
  sql += `INSERT INTO \`creature_template_movement\` (\`CreatureId\`, \`Ground\`, \`Swim\`, \`Flight\`, \`Rooted\`, \`Chase\`, \`Random\`, \`InteractionPauseTimer\`) VALUES\n`;
  sql += `(${entry}, ${mov_ground}, ${mov_swim}, ${mov_flight}, ${mov_rooted}, ${mov_chase}, ${mov_random}, NULL);\n`;

  return sql;
}
